services:
  - type: web
    name: guess-me-if-you-can
    env: python
    buildCommand: pip install -r requirements.txt && python app.py
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
